version: '3.8'

services:
  nextjs:
    build: .
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: yourpassword    # Ensure passwords and other environment variables are consistent
      POSTGRES_DB: yourdatabase          # Consistent database name
      POSTGRES_USER: root                # Make sure user matches what is used
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Expose the PostgreSQL port to allow external connections if needed
    networks:
      - mynetwork

volumes:
  dbdata:
    driver: local

networks:
  mynetwork:
    driver: bridge  # Explicitly define the network driver, which is bridge by default
